# User config
author: "barney"
tagline: "Adopt Barney, a 2 year old loveable German Shepherd/Belgian Malinois Mix"
description: "hi! i'm barney! i'm a two year old german shepherd & belgian malinois mix looking for my forever home. i'm loving, curious, energetic, intelligent, and kind and would love to be your new best friend <3"
keywords: "Barney, Dog, Adoption, Foster"
email: "shraeya[dot]iyer[at]gmail[dot]com"

# Site config
baseurl: "/adoptbarney"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed